"""
Verify problematic circuits by comparing noisy simulator vs real device execution
Uses Total Variation Distance (TVD) to quantify the discrepancy
Circuits are loaded from tmp/circuits/ (generated by analyze_problematic_segments.py)
"""
from pathlib import Path
import glob
from qiskit import qpy
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from .quantum_executor import QuantumExecutor
from .quantum_utils import calculate_tvd
import json
from collections import defaultdict


def project_counts(counts, measured_qubits, measure_map):
    """
    Project measurement results to specified qubits
    (Same logic as in delta_debug.py)
    
    Args:
        counts: Full measurement counts dict
        measured_qubits: List of measured qubit indices (sorted)
        measure_map: Dict mapping qubit_idx -> clbit_idx
        
    Returns:
        Projected counts dict
    """
    acc = defaultdict(int)
    clbits_in_order = [measure_map[q] for q in measured_qubits]
    
    for k, v in (counts or {}).items():
        bits = k.replace(" ", "")
        try:
            projected_bits = ''.join(bits[::-1][c] for c in clbits_in_order)
            acc[projected_bits] += v
        except IndexError:
            continue
    return dict(acc)


def verify_circuits(
    config_file: str = 'quantum_config.json',
    circuits_dir: str = 'tmp/circuits',
    output_file: str = 'tmp/circuit_comparison_results.json'
):
    """
    Verify problematic circuits by comparing noisy simulator vs real device.
    Loads circuits from tmp/circuits/ and calculates TVD for each.
    """
    # Initialize executor
    print("🔧 Initializing Quantum Executor...")
    qe = QuantumExecutor(config_file=config_file)
    
    # Find all QPY files in tmp/circuits
    qpy_files = sorted(glob.glob(str(Path(circuits_dir) / '*.qpy')))
    print(f"📁 Found {len(qpy_files)} QPY files\n")
    
    if not qpy_files:
        print(f"❌ No QPY files found in {circuits_dir}/")
        return
    
    results = []
    
    for qpy_file in qpy_files:
        print(f"{'='*70}")
        print(f"Processing: {Path(qpy_file).name}")
        print(f"{'='*70}")
        
        # Load circuit
        try:
            with open(qpy_file, 'rb') as f:
                circuit = list(qpy.load(f))[0]
        except Exception as e:
            print(f"❌ Failed to load circuit: {e}")
            continue
        
        print(f"Circuit: {circuit.num_qubits} qubits, {len(circuit.data)} instructions")
        
        # Extract physical qubit mapping from metadata (either from circuit or metadata file)
        physical_qubits = []
        qubit_mapping = {}
        
        # First try to get from circuit metadata
        if hasattr(circuit, 'metadata') and circuit.metadata:
            physical_qubits = circuit.metadata.get('physical_qubits', [])
            qubit_mapping = circuit.metadata.get('qubit_mapping', {})
        
        # If not in circuit, try to load from separate metadata JSON file
        if not physical_qubits:
            metadata_file = qpy_file.replace('.qpy', '_metadata.json')
            if Path(metadata_file).exists():
                try:
                    with open(metadata_file, 'r') as f:
                        metadata = json.load(f)
                        physical_qubits = metadata.get('physical_qubits', [])
                        qubit_mapping = metadata.get('qubit_mapping', {})
                except Exception as e:
                    print(f"⚠️  Failed to load metadata file: {e}")
        
        if physical_qubits:
            print(f"Physical qubits: {physical_qubits}")
            print(f"Virtual→Physical mapping: {qubit_mapping}")
            
            # If we have physical qubit info, we need to remap the circuit to use those physical qubits
            # This requires transpiling with initial_layout
            print(f"⚠️  Note: Circuit will be transpiled to use physical qubits {physical_qubits}")
        
        # Extract measured qubits and measurement mapping
        measured_qubits_set = set()
        measure_map = {}
        for inst in circuit.data:
            if inst.operation.name == "measure":
                q_idx = circuit.find_bit(inst.qubits[0]).index
                c_idx = circuit.find_bit(inst.clbits[0]).index
                measured_qubits_set.add(q_idx)
                measure_map[q_idx] = c_idx
        
        # If no measurements, add measurements to all qubits
        if not measured_qubits_set:
            print("⚠️  No measurements found, adding measurements to all qubits...")
            # Need to ensure circuit has enough classical bits
            if circuit.num_clbits < circuit.num_qubits:
                from qiskit import ClassicalRegister
                # Add classical bits if needed
                additional_clbits = circuit.num_qubits - circuit.num_clbits
                cr = ClassicalRegister(additional_clbits, 'c_added')
                circuit.add_register(cr)
            
            # Add measurements
            for q_idx in range(circuit.num_qubits):
                circuit.measure(q_idx, q_idx)
                measured_qubits_set.add(q_idx)
                measure_map[q_idx] = q_idx
            
            print(f"   Added measurements to qubits: {list(range(circuit.num_qubits))}")
        
        measured_qubits = sorted(list(measured_qubits_set))
        print(f"Measured virtual qubits: {measured_qubits}")
        
        # Display physical qubit mapping for measured qubits
        if physical_qubits:
            measured_physical_qubits = [physical_qubits[q] for q in measured_qubits if q < len(physical_qubits)]
            print(f"Measured physical qubits: {measured_physical_qubits}")
        
        print(f"Measurement mapping: virtual_qubit→clbit {measure_map}")
        
        # If we have physical qubit info, remap circuit to use those physical qubits
        # This creates a larger circuit with the operations on the correct physical qubits
        if physical_qubits and len(physical_qubits) > 0 and qubit_mapping:
            print(f"\n🔧 Remapping circuit to use original physical qubits {physical_qubits}...")
            try:
                from qiskit import QuantumCircuit, ClassicalRegister
                
                # Determine the required circuit size
                max_physical_qubit = max(physical_qubits)
                num_physical_qubits = max_physical_qubit + 1
                
                # Create new circuit with full size
                new_qc = QuantumCircuit(num_physical_qubits, len(physical_qubits))
                
                # Copy operations from old circuit to new circuit using physical qubit indices
                for inst in circuit.data:
                    if inst.operation.name == "measure":
                        # Skip measurements for now, we'll add them later
                        continue
                    
                    # Map virtual qubits to physical qubits
                    physical_qubit_indices = []
                    for virt_q in inst.qubits:
                        virt_idx = circuit.find_bit(virt_q).index
                        if virt_idx < len(physical_qubits):
                            physical_qubit_indices.append(physical_qubits[virt_idx])
                        else:
                            print(f"⚠️  Warning: virtual qubit {virt_idx} not in physical_qubits")
                            physical_qubit_indices.append(virt_idx)
                    
                    # Apply operation on physical qubits
                    if len(physical_qubit_indices) == 1:
                        new_qc.append(inst.operation, [physical_qubit_indices[0]])
                    elif len(physical_qubit_indices) == 2:
                        new_qc.append(inst.operation, [physical_qubit_indices[0], physical_qubit_indices[1]])
                    else:
                        new_qc.append(inst.operation, physical_qubit_indices)
                
                # Add measurements on physical qubits
                for i, phys_q in enumerate(physical_qubits):
                    new_qc.measure(phys_q, i)
                
                # Replace circuit with remapped version
                circuit = new_qc
                
                # Update measurement mapping
                measured_qubits_set = set(physical_qubits)
                measure_map = {phys_q: i for i, phys_q in enumerate(physical_qubits)}
                measured_qubits = sorted(list(measured_qubits_set))
                
                print(f"✅ Circuit remapped to {num_physical_qubits} qubits")
                print(f"   Operations now on physical qubits: {physical_qubits}")
                print(f"   Measured qubits: {measured_qubits}")
                
            except Exception as e:
                print(f"⚠️  Remapping failed: {e}")
                print(f"   Will run circuit as-is on default qubits")
                import traceback
                traceback.print_exc()
        
        # Run noisy simulator
        print("\n🔧 Running noisy simulator (baseline)...")
        noisy_result = qe.run_circuit(circuit, execution_type='noisy_simulator')
        
        if not noisy_result.get('success'):
            print(f"❌ Noisy simulator failed: {noisy_result.get('error')}")
            continue
        
        noisy_counts_raw = noisy_result.get('counts', {})
        noisy_counts = project_counts(noisy_counts_raw, measured_qubits, measure_map)
        print(f"✅ Noisy simulator completed")
        print(f"   Projected counts: {noisy_counts}")
        
        # Run real device
        print("\n🚀 Running real device (test)...")
        real_result = qe.run_circuit(circuit, execution_type='real_device')
        
        if not real_result.get('success'):
            print(f"⚠️  Real device failed: {real_result.get('error')}")
            print("🔄 Retrying once...")
            real_result = qe.run_circuit(circuit, execution_type='real_device')
        
        if not real_result.get('success'):
            print(f"❌ Real device failed again: {real_result.get('error')}")
            continue
        
        real_counts_raw = real_result.get('counts', {})
        real_counts = project_counts(real_counts_raw, measured_qubits, measure_map)
        print(f"✅ Real device completed (Job ID: {real_result.get('job_id')})")
        print(f"   Projected counts: {real_counts}")
        
        # Calculate Total Variation Distance
        tvd_loss, state_details = calculate_tvd(noisy_counts, real_counts)
        
        print(f"\n📊 Total Variation Distance (TVD Loss): {tvd_loss:.6f}")
        print(f"\n   State-by-state breakdown:")
        print(f"   {'State':<10} {'Noisy Prob':<12} {'Real Prob':<12} {'|Diff|':<10} {'Noisy Count':<12} {'Real Count':<12}")
        print(f"   {'-'*68}")
        for state in sorted(state_details.keys()):
            detail = state_details[state]
            print(f"   {state:<10} {detail['noisy_prob']:<12.6f} {detail['real_prob']:<12.6f} "
                  f"{detail['abs_diff']:<10.6f} {detail['noisy_count']:<12} {detail['real_count']:<12}")
        
        # Store result
        result_entry = {
            'file': Path(qpy_file).name,
            'file_path': qpy_file,
            'num_qubits': circuit.num_qubits,
            'num_instructions': len(circuit.data),
            'measured_virtual_qubits': measured_qubits,
            'measured_physical_qubits': [physical_qubits[q] for q in measured_qubits if q < len(physical_qubits)] if physical_qubits else None,
            'physical_qubits': physical_qubits if physical_qubits else None,
            'qubit_mapping': {f"v{k}": f"p{v}" for k, v in qubit_mapping.items()} if qubit_mapping else None,
            'measure_map': {f"v{k}": f"c{v}" for k, v in measure_map.items()},
            'tvd_loss': tvd_loss,
            'noisy_counts': noisy_counts,
            'real_counts': real_counts,
            'state_details': state_details,
            'job_id': real_result.get('job_id'),
            'backend': real_result.get('backend')
        }
        results.append(result_entry)
        print()
    
    # Summary
    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Total circuits processed: {len(results)}")
    
    if results:
        print(f"\n{'Circuit File':<35} {'TVD Loss':<15} {'Job ID'}")
        print(f"{'-'*70}")
        for r in sorted(results, key=lambda x: x['tvd_loss'], reverse=True):
            job_id = r.get('job_id', 'N/A')
            print(f"{r['file']:<35} {r['tvd_loss']:<15.6f} {job_id}")
        
        # Statistics
        losses = [r['tvd_loss'] for r in results]
        print(f"\nStatistics:")
        print(f"  Average TVD Loss: {sum(losses)/len(losses):.6f}")
        print(f"  Max TVD Loss:     {max(losses):.6f} ({[r['file'] for r in results if r['tvd_loss'] == max(losses)][0]})")
        print(f"  Min TVD Loss:     {min(losses):.6f} ({[r['file'] for r in results if r['tvd_loss'] == min(losses)][0]})")
        
        # Save results to JSON
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            json.dump(results, f, indent=2)
        print(f"\n✅ Detailed results saved to: {output_path}")
    else:
        print("⚠️  No circuits were successfully processed")

